# coding: utf-8

"""
    Hostinger Mail API Python SDK

    API Version: 1.0.2

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_mail_api.models.v1_send_attachment import V1SendAttachment

class TestV1SendAttachment(unittest.TestCase):
    """V1SendAttachment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1SendAttachment:
        """Test V1SendAttachment
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1SendAttachment`
        """
        model = V1SendAttachment()
        if include_optional:
            return V1SendAttachment(
                filename = 'invoice.pdf',
                content = 'JVBERi0xLjQK...',
                content_type = 'application/pdf',
                cid = 'logo',
                encoding = 'base64'
            )
        else:
            return V1SendAttachment(
                filename = 'invoice.pdf',
                content = 'JVBERi0xLjQK...',
        )
        """

    def testV1SendAttachment(self):
        """Test V1SendAttachment"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
