# coding: utf-8

"""
    Hostinger Mail API Python SDK

    API Version: 1.1.0

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_mail_api.models.v1_quota_quota_resource import V1QuotaQuotaResource

class TestV1QuotaQuotaResource(unittest.TestCase):
    """V1QuotaQuotaResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1QuotaQuotaResource:
        """Test V1QuotaQuotaResource
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1QuotaQuotaResource`
        """
        model = V1QuotaQuotaResource()
        if include_optional:
            return V1QuotaQuotaResource(
                resource_name = 'STORAGE',
                usage = 1048576,
                limit = 1073741824,
                percentage = 0
            )
        else:
            return V1QuotaQuotaResource(
                resource_name = 'STORAGE',
                usage = 1048576,
                limit = 1073741824,
                percentage = 0,
        )
        """

    def testV1QuotaQuotaResource(self):
        """Test V1QuotaQuotaResource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
