# coding: utf-8

"""
    Hostinger Email API Python SDK

    API Version: 1.0.0

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_email_api.api.send_api import SendApi


class TestSendApi(unittest.TestCase):
    """SendApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SendApi()

    def tearDown(self) -> None:
        pass

    def test_send_email(self) -> None:
        """Test case for send_email

        Send email
        """
        pass


if __name__ == '__main__':
    unittest.main()
