# coding: utf-8

"""
    Hostinger Mail API Python SDK

    API Version: 1.2.1

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_mail_api.api.feedback_api import FeedbackApi


class TestFeedbackApi(unittest.TestCase):
    """FeedbackApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FeedbackApi()

    def tearDown(self) -> None:
        pass

    def test_submit_feedback(self) -> None:
        """Test case for submit_feedback

        Submit feedback
        """
        pass


if __name__ == '__main__':
    unittest.main()
