# coding: utf-8

"""
    Hostinger Mail API Python SDK

    API Version: 1.0.3

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_mail_api.models.v1_folders_resource import V1FoldersResource

class TestV1FoldersResource(unittest.TestCase):
    """V1FoldersResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1FoldersResource:
        """Test V1FoldersResource
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1FoldersResource`
        """
        model = V1FoldersResource()
        if include_optional:
            return V1FoldersResource(
                data = hostinger_mail_api.models.v1/folders/folder.V1.Folders.Folder(
                    path = 'INBOX.Sent', 
                    name = 'Sent', 
                    delimiter = '.', 
                    special_use = '\Sent', 
                    message_count = 42, 
                    unread_count = 5, )
            )
        else:
            return V1FoldersResource(
                data = hostinger_mail_api.models.v1/folders/folder.V1.Folders.Folder(
                    path = 'INBOX.Sent', 
                    name = 'Sent', 
                    delimiter = '.', 
                    special_use = '\Sent', 
                    message_count = 42, 
                    unread_count = 5, ),
        )
        """

    def testV1FoldersResource(self):
        """Test V1FoldersResource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
