# coding: utf-8

"""
    Hostinger Mail API Python SDK

    API Version: 1.0.2

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_mail_api.api.webhooks_api import WebhooksApi


class TestWebhooksApi(unittest.TestCase):
    """WebhooksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WebhooksApi()

    def tearDown(self) -> None:
        pass

    def test_create_webhook(self) -> None:
        """Test case for create_webhook

        Create webhook
        """
        pass

    def test_delete_webhook(self) -> None:
        """Test case for delete_webhook

        Delete webhook
        """
        pass

    def test_get_webhook(self) -> None:
        """Test case for get_webhook

        Get webhook
        """
        pass

    def test_list_webhooks(self) -> None:
        """Test case for list_webhooks

        List webhooks
        """
        pass

    def test_regenerate_webhook_secret(self) -> None:
        """Test case for regenerate_webhook_secret

        Regenerate webhook secret
        """
        pass

    def test_test_webhook(self) -> None:
        """Test case for test_webhook

        Test webhook
        """
        pass

    def test_update_webhook(self) -> None:
        """Test case for update_webhook

        Update webhook
        """
        pass


if __name__ == '__main__':
    unittest.main()
