# coding: utf-8

"""
    Hostinger Email API Python SDK

    API Version: 1.0.0

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_mail_api.models.v1_me_resource_data import V1MeResourceData

class TestV1MeResourceData(unittest.TestCase):
    """V1MeResourceData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1MeResourceData:
        """Test V1MeResourceData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1MeResourceData`
        """
        model = V1MeResourceData()
        if include_optional:
            return V1MeResourceData(
                order_resource_id = 'OR1a2b3c4d5e6f7g',
                mailboxes = [
                    hostinger_mail_api.models.v1/me/mailbox.V1.Me.Mailbox(
                        resource_id = 'AC1a2b3c4d5e6f7g', 
                        address = 'user@example.com', )
                    ]
            )
        else:
            return V1MeResourceData(
                order_resource_id = 'OR1a2b3c4d5e6f7g',
                mailboxes = [
                    hostinger_mail_api.models.v1/me/mailbox.V1.Me.Mailbox(
                        resource_id = 'AC1a2b3c4d5e6f7g', 
                        address = 'user@example.com', )
                    ],
        )
        """

    def testV1MeResourceData(self):
        """Test V1MeResourceData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
