# coding: utf-8

"""
    Hostinger Mail API Python SDK

    API Version: 1.2.1

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_mail_api.models.v1_feedback_submit_request import V1FeedbackSubmitRequest

class TestV1FeedbackSubmitRequest(unittest.TestCase):
    """V1FeedbackSubmitRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1FeedbackSubmitRequest:
        """Test V1FeedbackSubmitRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1FeedbackSubmitRequest`
        """
        model = V1FeedbackSubmitRequest()
        if include_optional:
            return V1FeedbackSubmitRequest(
                score = 3,
                message = 'POST /api/v1/mailboxes/{mailboxResourceId}/send returned 502 after 30 seconds for a message with a 10 MB attachment.'
            )
        else:
            return V1FeedbackSubmitRequest(
                score = 3,
                message = 'POST /api/v1/mailboxes/{mailboxResourceId}/send returned 502 after 30 seconds for a message with a 10 MB attachment.',
        )
        """

    def testV1FeedbackSubmitRequest(self):
        """Test V1FeedbackSubmitRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
