# coding: utf-8

"""
    Hostinger Email API Python SDK

    API Version: 1.0.0

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_email_api.models.v1_send_request import V1SendRequest

class TestV1SendRequest(unittest.TestCase):
    """V1SendRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1SendRequest:
        """Test V1SendRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1SendRequest`
        """
        model = V1SendRequest()
        if include_optional:
            return V1SendRequest(
                to = ["recipient@example.com"],
                display_name = 'John Doe',
                cc = ["cc@example.com"],
                bcc = ["bcc@example.com"],
                subject = 'Hello',
                text = 'Plain body',
                html = '<p>HTML body</p>',
                attachments = [
                    hostinger_email_api.models.v1/send/attachment.V1.Send.Attachment(
                        filename = 'invoice.pdf', 
                        content = 'JVBERi0xLjQK...', 
                        content_type = 'application/pdf', 
                        cid = 'logo', 
                        encoding = 'base64', )
                    ]
            )
        else:
            return V1SendRequest(
        )
        """

    def testV1SendRequest(self):
        """Test V1SendRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
