# coding: utf-8

"""
    Hostinger Mail API Python SDK

    API Version: 1.1.0

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_mail_api.models.v1_folder_messages_message_text_resource import V1FolderMessagesMessageTextResource

class TestV1FolderMessagesMessageTextResource(unittest.TestCase):
    """V1FolderMessagesMessageTextResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1FolderMessagesMessageTextResource:
        """Test V1FolderMessagesMessageTextResource
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1FolderMessagesMessageTextResource`
        """
        model = V1FolderMessagesMessageTextResource()
        if include_optional:
            return V1FolderMessagesMessageTextResource(
                data = hostinger_mail_api.models.v1/folder_messages/message_text.V1.FolderMessages.MessageText(
                    text = 'Hello world', 
                    html = '<p>Hello world</p>', )
            )
        else:
            return V1FolderMessagesMessageTextResource(
                data = hostinger_mail_api.models.v1/folder_messages/message_text.V1.FolderMessages.MessageText(
                    text = 'Hello world', 
                    html = '<p>Hello world</p>', ),
        )
        """

    def testV1FolderMessagesMessageTextResource(self):
        """Test V1FolderMessagesMessageTextResource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
