# coding: utf-8

"""
    Hostinger Mail API Python SDK

    API Version: 1.0.3

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_mail_api.api.folders_api import FoldersApi


class TestFoldersApi(unittest.TestCase):
    """FoldersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FoldersApi()

    def tearDown(self) -> None:
        pass

    def test_create_folder(self) -> None:
        """Test case for create_folder

        Create folder
        """
        pass

    def test_delete_folder(self) -> None:
        """Test case for delete_folder

        Delete folder
        """
        pass

    def test_list_folders(self) -> None:
        """Test case for list_folders

        List folders
        """
        pass

    def test_update_folder(self) -> None:
        """Test case for update_folder

        Update folder
        """
        pass


if __name__ == '__main__':
    unittest.main()
