# coding: utf-8

"""
    Hostinger Email API Python SDK

    API Version: 1.0.0

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_email_api.models.v1_folder_messages_message_text import V1FolderMessagesMessageText

class TestV1FolderMessagesMessageText(unittest.TestCase):
    """V1FolderMessagesMessageText unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1FolderMessagesMessageText:
        """Test V1FolderMessagesMessageText
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1FolderMessagesMessageText`
        """
        model = V1FolderMessagesMessageText()
        if include_optional:
            return V1FolderMessagesMessageText(
                text = 'Hello world',
                html = '<p>Hello world</p>'
            )
        else:
            return V1FolderMessagesMessageText(
                text = 'Hello world',
                html = '<p>Hello world</p>',
        )
        """

    def testV1FolderMessagesMessageText(self):
        """Test V1FolderMessagesMessageText"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
