# coding: utf-8

"""
    Hostinger Mail API Python SDK

    API Version: 1.0.3

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_mail_api.models.v1_folders_folder import V1FoldersFolder

class TestV1FoldersFolder(unittest.TestCase):
    """V1FoldersFolder unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1FoldersFolder:
        """Test V1FoldersFolder
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1FoldersFolder`
        """
        model = V1FoldersFolder()
        if include_optional:
            return V1FoldersFolder(
                path = 'INBOX.Sent',
                name = 'Sent',
                delimiter = '.',
                special_use = '\Sent',
                message_count = 42,
                unread_count = 5
            )
        else:
            return V1FoldersFolder(
                path = 'INBOX.Sent',
                name = 'Sent',
                delimiter = '.',
                special_use = '\Sent',
                message_count = 42,
                unread_count = 5,
        )
        """

    def testV1FoldersFolder(self):
        """Test V1FoldersFolder"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
