# coding: utf-8

"""
    Hostinger Mail API Python SDK

    API Version: 1.1.0

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_mail_api.models.v1_me_resource import V1MeResource

class TestV1MeResource(unittest.TestCase):
    """V1MeResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1MeResource:
        """Test V1MeResource
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1MeResource`
        """
        model = V1MeResource()
        if include_optional:
            return V1MeResource(
                data = hostinger_mail_api.models.v1_me_resource_data.V1_Me_Resource_data(
                    order_resource_id = 'OR1a2b3c4d5e6f7g', 
                    mailboxes = [
                        hostinger_mail_api.models.v1/me/mailbox.V1.Me.Mailbox(
                            resource_id = 'AC1a2b3c4d5e6f7g', 
                            address = 'user@example.com', )
                        ], )
            )
        else:
            return V1MeResource(
                data = hostinger_mail_api.models.v1_me_resource_data.V1_Me_Resource_data(
                    order_resource_id = 'OR1a2b3c4d5e6f7g', 
                    mailboxes = [
                        hostinger_mail_api.models.v1/me/mailbox.V1.Me.Mailbox(
                            resource_id = 'AC1a2b3c4d5e6f7g', 
                            address = 'user@example.com', )
                        ], ),
        )
        """

    def testV1MeResource(self):
        """Test V1MeResource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
