# coding: utf-8

"""
    Hostinger Email API Python SDK

    API Version: 1.0.0

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_email_api.models.v1_folder_messages_resource import V1FolderMessagesResource

class TestV1FolderMessagesResource(unittest.TestCase):
    """V1FolderMessagesResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1FolderMessagesResource:
        """Test V1FolderMessagesResource
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1FolderMessagesResource`
        """
        model = V1FolderMessagesResource()
        if include_optional:
            return V1FolderMessagesResource(
                data = hostinger_email_api.models.v1/folder_messages/message.V1.FolderMessages.Message(
                    uid = 123, 
                    path = 'INBOX', 
                    date = '2024-01-15T10:30Z', 
                    flags = ["\\Seen","\\Flagged"], 
                    unseen = False, 
                    size = 2048, 
                    subject = 'Test Email Subject', 
                    from = hostinger_email_api.models.v1/folder_messages/message_address.V1.FolderMessages.MessageAddress(
                        name = 'John Doe', 
                        address = 'john@example.com', ), 
                    to = [
                        hostinger_email_api.models.v1/folder_messages/message_address.V1.FolderMessages.MessageAddress(
                            name = 'John Doe', 
                            address = 'john@example.com', )
                        ], 
                    cc = [
                        
                        ], 
                    bcc = [
                        
                        ], 
                    message_id = '<1234567890@example.com>', 
                    in_reply_to = '<0987654321@example.com>', 
                    attachments = [
                        hostinger_email_api.models.v1/folder_messages/message_attachment.V1.FolderMessages.MessageAttachment(
                            id = 'YXR0YWNobWVudDpJTkJPWDoxMjM6MS4y', 
                            content_type = 'application/pdf', 
                            size_bytes = 1024, 
                            inline = False, 
                            filename = 'document.pdf', 
                            content_id = '<attachment@example.com>', )
                        ], )
            )
        else:
            return V1FolderMessagesResource(
                data = hostinger_email_api.models.v1/folder_messages/message.V1.FolderMessages.Message(
                    uid = 123, 
                    path = 'INBOX', 
                    date = '2024-01-15T10:30Z', 
                    flags = ["\\Seen","\\Flagged"], 
                    unseen = False, 
                    size = 2048, 
                    subject = 'Test Email Subject', 
                    from = hostinger_email_api.models.v1/folder_messages/message_address.V1.FolderMessages.MessageAddress(
                        name = 'John Doe', 
                        address = 'john@example.com', ), 
                    to = [
                        hostinger_email_api.models.v1/folder_messages/message_address.V1.FolderMessages.MessageAddress(
                            name = 'John Doe', 
                            address = 'john@example.com', )
                        ], 
                    cc = [
                        
                        ], 
                    bcc = [
                        
                        ], 
                    message_id = '<1234567890@example.com>', 
                    in_reply_to = '<0987654321@example.com>', 
                    attachments = [
                        hostinger_email_api.models.v1/folder_messages/message_attachment.V1.FolderMessages.MessageAttachment(
                            id = 'YXR0YWNobWVudDpJTkJPWDoxMjM6MS4y', 
                            content_type = 'application/pdf', 
                            size_bytes = 1024, 
                            inline = False, 
                            filename = 'document.pdf', 
                            content_id = '<attachment@example.com>', )
                        ], ),
        )
        """

    def testV1FolderMessagesResource(self):
        """Test V1FolderMessagesResource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
