# coding: utf-8

"""
    Hostinger Mail API Python SDK

    API Version: 1.1.0

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_mail_api.models.v1_webhooks_webhook_with_secret import V1WebhooksWebhookWithSecret

class TestV1WebhooksWebhookWithSecret(unittest.TestCase):
    """V1WebhooksWebhookWithSecret unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1WebhooksWebhookWithSecret:
        """Test V1WebhooksWebhookWithSecret
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1WebhooksWebhookWithSecret`
        """
        model = V1WebhooksWebhookWithSecret()
        if include_optional:
            return V1WebhooksWebhookWithSecret(
                id = '019683f8-1234-7abc-8def-0123456789ab',
                account_resource_id = 'AC1a2b3c4d5e6f7g',
                mailbox = 'user@example.com',
                name = 'New message notifier',
                description = 'Notifies our CRM when a new email arrives',
                events = [
                    'message.received'
                    ],
                status = 'active',
                url = 'https://example.com/webhooks/incoming',
                created_at = '2026-04-07T12:00Z',
                updated_at = '2026-04-07T12:00Z',
                secret = '4a6f8b2d1e9c3f7a0b5d8e2c4f1a7b3d9e6c2f8a1b4d7e0c3f6a9b2d5e8c1f4'
            )
        else:
            return V1WebhooksWebhookWithSecret(
                id = '019683f8-1234-7abc-8def-0123456789ab',
                account_resource_id = 'AC1a2b3c4d5e6f7g',
                mailbox = 'user@example.com',
                name = 'New message notifier',
                description = 'Notifies our CRM when a new email arrives',
                events = [
                    'message.received'
                    ],
                status = 'active',
                url = 'https://example.com/webhooks/incoming',
                created_at = '2026-04-07T12:00Z',
                updated_at = '2026-04-07T12:00Z',
                secret = '4a6f8b2d1e9c3f7a0b5d8e2c4f1a7b3d9e6c2f8a1b4d7e0c3f6a9b2d5e8c1f4',
        )
        """

    def testV1WebhooksWebhookWithSecret(self):
        """Test V1WebhooksWebhookWithSecret"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
