# coding: utf-8

"""
    Hostinger Mail API Python SDK

    API Version: 1.0.2

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_mail_api.models.v1_folder_messages_move_bulk_request import V1FolderMessagesMoveBulkRequest

class TestV1FolderMessagesMoveBulkRequest(unittest.TestCase):
    """V1FolderMessagesMoveBulkRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1FolderMessagesMoveBulkRequest:
        """Test V1FolderMessagesMoveBulkRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1FolderMessagesMoveBulkRequest`
        """
        model = V1FolderMessagesMoveBulkRequest()
        if include_optional:
            return V1FolderMessagesMoveBulkRequest(
                uids = [42,43,44],
                target_folder = 'INBOX.Sent'
            )
        else:
            return V1FolderMessagesMoveBulkRequest(
                uids = [42,43,44],
                target_folder = 'INBOX.Sent',
        )
        """

    def testV1FolderMessagesMoveBulkRequest(self):
        """Test V1FolderMessagesMoveBulkRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
