# coding: utf-8

"""
    Hostinger Mail API Python SDK

    API Version: 1.0.3

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_mail_api.models.v1_webhooks_resource import V1WebhooksResource

class TestV1WebhooksResource(unittest.TestCase):
    """V1WebhooksResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1WebhooksResource:
        """Test V1WebhooksResource
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1WebhooksResource`
        """
        model = V1WebhooksResource()
        if include_optional:
            return V1WebhooksResource(
                data = hostinger_mail_api.models.v1/webhooks/webhook.V1.Webhooks.Webhook(
                    id = '019683f8-1234-7abc-8def-0123456789ab', 
                    account_resource_id = 'AC1a2b3c4d5e6f7g', 
                    mailbox = 'user@example.com', 
                    name = 'New message notifier', 
                    description = 'Notifies our CRM when a new email arrives', 
                    events = [
                        'message.received'
                        ], 
                    status = 'active', 
                    url = 'https://example.com/webhooks/incoming', 
                    created_at = '2026-04-07T12:00Z', 
                    updated_at = '2026-04-07T12:00Z', )
            )
        else:
            return V1WebhooksResource(
                data = hostinger_mail_api.models.v1/webhooks/webhook.V1.Webhooks.Webhook(
                    id = '019683f8-1234-7abc-8def-0123456789ab', 
                    account_resource_id = 'AC1a2b3c4d5e6f7g', 
                    mailbox = 'user@example.com', 
                    name = 'New message notifier', 
                    description = 'Notifies our CRM when a new email arrives', 
                    events = [
                        'message.received'
                        ], 
                    status = 'active', 
                    url = 'https://example.com/webhooks/incoming', 
                    created_at = '2026-04-07T12:00Z', 
                    updated_at = '2026-04-07T12:00Z', ),
        )
        """

    def testV1WebhooksResource(self):
        """Test V1WebhooksResource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
