# coding: utf-8

"""
    Hostinger Mail API Python SDK

    API Version: 1.0.2

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_mail_api.api.quota_api import QuotaApi


class TestQuotaApi(unittest.TestCase):
    """QuotaApi unit test stubs"""

    def setUp(self) -> None:
        self.api = QuotaApi()

    def tearDown(self) -> None:
        pass

    def test_get_quota(self) -> None:
        """Test case for get_quota

        Get mailbox quota
        """
        pass


if __name__ == '__main__':
    unittest.main()
