# coding: utf-8

"""
    Hostinger Mail API Python SDK

    API Version: 1.0.3

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_mail_api.models.v1_folders_create_request import V1FoldersCreateRequest

class TestV1FoldersCreateRequest(unittest.TestCase):
    """V1FoldersCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1FoldersCreateRequest:
        """Test V1FoldersCreateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1FoldersCreateRequest`
        """
        model = V1FoldersCreateRequest()
        if include_optional:
            return V1FoldersCreateRequest(
                name = 'Projects'
            )
        else:
            return V1FoldersCreateRequest(
                name = 'Projects',
        )
        """

    def testV1FoldersCreateRequest(self):
        """Test V1FoldersCreateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
