# coding: utf-8

"""
    Hostinger Mail API Python SDK

    API Version: 1.0.2

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_mail_api.api.messages_api import MessagesApi


class TestMessagesApi(unittest.TestCase):
    """MessagesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MessagesApi()

    def tearDown(self) -> None:
        pass

    def test_delete_all_messages(self) -> None:
        """Test case for delete_all_messages

        Delete all messages
        """
        pass

    def test_delete_message(self) -> None:
        """Test case for delete_message

        Delete message
        """
        pass

    def test_delete_messages(self) -> None:
        """Test case for delete_messages

        Delete messages
        """
        pass

    def test_get_message(self) -> None:
        """Test case for get_message

        Get message
        """
        pass

    def test_get_message_attachment(self) -> None:
        """Test case for get_message_attachment

        Download message attachment
        """
        pass

    def test_get_message_source(self) -> None:
        """Test case for get_message_source

        Get message source
        """
        pass

    def test_get_message_text(self) -> None:
        """Test case for get_message_text

        Get message text content
        """
        pass

    def test_list_messages(self) -> None:
        """Test case for list_messages

        List messages
        """
        pass

    def test_move_message(self) -> None:
        """Test case for move_message

        Move message
        """
        pass

    def test_move_messages(self) -> None:
        """Test case for move_messages

        Move messages
        """
        pass

    def test_patch_message(self) -> None:
        """Test case for patch_message

        Update message flags
        """
        pass

    def test_search_messages(self) -> None:
        """Test case for search_messages

        Search messages
        """
        pass

    def test_update_message_flags(self) -> None:
        """Test case for update_message_flags

        Update message flags
        """
        pass


if __name__ == '__main__':
    unittest.main()
