# coding: utf-8

"""
    Hostinger Mail API Python SDK

    API Version: 1.1.0

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_mail_api.api.account_api import AccountApi


class TestAccountApi(unittest.TestCase):
    """AccountApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AccountApi()

    def tearDown(self) -> None:
        pass

    def test_get_current_account(self) -> None:
        """Test case for get_current_account

        Get the authenticated account
        """
        pass


if __name__ == '__main__':
    unittest.main()
