# coding: utf-8

"""
    Hostinger Mail API Python SDK

    API Version: 1.0.3

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_mail_api.models.v1_folder_messages_search_request import V1FolderMessagesSearchRequest

class TestV1FolderMessagesSearchRequest(unittest.TestCase):
    """V1FolderMessagesSearchRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1FolderMessagesSearchRequest:
        """Test V1FolderMessagesSearchRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1FolderMessagesSearchRequest`
        """
        model = V1FolderMessagesSearchRequest()
        if include_optional:
            return V1FolderMessagesSearchRequest(
                since = 'Mon Jan 01 00:00:00 UTC 2024',
                before = 'Tue Dec 31 00:00:00 UTC 2024',
                flags = ["\\Seen","\\Flagged"],
                uid = '1:100',
                subject = 'meeting',
                var_from = 'john@example.com',
                to = 'jane@example.com',
                cc = 'team@example.com',
                body = 'important',
                header = 'X-Custom-Header:value',
                larger = 1024,
                smaller = 1048576,
                text = 'urgent'
            )
        else:
            return V1FolderMessagesSearchRequest(
        )
        """

    def testV1FolderMessagesSearchRequest(self):
        """Test V1FolderMessagesSearchRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
