# coding: utf-8

"""
    Hostinger Email API Python SDK

    API Version: 1.0.0

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_mail_api.models.v1_folder_messages_move_request import V1FolderMessagesMoveRequest

class TestV1FolderMessagesMoveRequest(unittest.TestCase):
    """V1FolderMessagesMoveRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1FolderMessagesMoveRequest:
        """Test V1FolderMessagesMoveRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1FolderMessagesMoveRequest`
        """
        model = V1FolderMessagesMoveRequest()
        if include_optional:
            return V1FolderMessagesMoveRequest(
                target_folder = 'INBOX.Sent'
            )
        else:
            return V1FolderMessagesMoveRequest(
                target_folder = 'INBOX.Sent',
        )
        """

    def testV1FolderMessagesMoveRequest(self):
        """Test V1FolderMessagesMoveRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
