# coding: utf-8

"""
    Hostinger Email API Python SDK

    API Version: 1.0.0

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_mail_api.models.v1_folder_messages_message import V1FolderMessagesMessage

class TestV1FolderMessagesMessage(unittest.TestCase):
    """V1FolderMessagesMessage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1FolderMessagesMessage:
        """Test V1FolderMessagesMessage
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1FolderMessagesMessage`
        """
        model = V1FolderMessagesMessage()
        if include_optional:
            return V1FolderMessagesMessage(
                uid = 123,
                path = 'INBOX',
                var_date = '2024-01-15T10:30Z',
                flags = ["\\Seen","\\Flagged"],
                unseen = False,
                size = 2048,
                subject = 'Test Email Subject',
                var_from = hostinger_mail_api.models.v1/folder_messages/message_address.V1.FolderMessages.MessageAddress(
                    name = 'John Doe', 
                    address = 'john@example.com', ),
                to = [
                    hostinger_mail_api.models.v1/folder_messages/message_address.V1.FolderMessages.MessageAddress(
                        name = 'John Doe', 
                        address = 'john@example.com', )
                    ],
                cc = [
                    hostinger_mail_api.models.v1/folder_messages/message_address.V1.FolderMessages.MessageAddress(
                        name = 'John Doe', 
                        address = 'john@example.com', )
                    ],
                bcc = [
                    hostinger_mail_api.models.v1/folder_messages/message_address.V1.FolderMessages.MessageAddress(
                        name = 'John Doe', 
                        address = 'john@example.com', )
                    ],
                message_id = '<1234567890@example.com>',
                in_reply_to = '<0987654321@example.com>',
                attachments = [
                    hostinger_mail_api.models.v1/folder_messages/message_attachment.V1.FolderMessages.MessageAttachment(
                        id = 'YXR0YWNobWVudDpJTkJPWDoxMjM6MS4y', 
                        content_type = 'application/pdf', 
                        size_bytes = 1024, 
                        inline = False, 
                        filename = 'document.pdf', 
                        content_id = '<attachment@example.com>', )
                    ]
            )
        else:
            return V1FolderMessagesMessage(
                uid = 123,
                path = 'INBOX',
                var_date = '2024-01-15T10:30Z',
                flags = ["\\Seen","\\Flagged"],
                unseen = False,
                size = 2048,
                subject = 'Test Email Subject',
                var_from = hostinger_mail_api.models.v1/folder_messages/message_address.V1.FolderMessages.MessageAddress(
                    name = 'John Doe', 
                    address = 'john@example.com', ),
                to = [
                    hostinger_mail_api.models.v1/folder_messages/message_address.V1.FolderMessages.MessageAddress(
                        name = 'John Doe', 
                        address = 'john@example.com', )
                    ],
                cc = [
                    hostinger_mail_api.models.v1/folder_messages/message_address.V1.FolderMessages.MessageAddress(
                        name = 'John Doe', 
                        address = 'john@example.com', )
                    ],
                bcc = [
                    hostinger_mail_api.models.v1/folder_messages/message_address.V1.FolderMessages.MessageAddress(
                        name = 'John Doe', 
                        address = 'john@example.com', )
                    ],
                message_id = '<1234567890@example.com>',
                in_reply_to = '<0987654321@example.com>',
                attachments = [
                    hostinger_mail_api.models.v1/folder_messages/message_attachment.V1.FolderMessages.MessageAttachment(
                        id = 'YXR0YWNobWVudDpJTkJPWDoxMjM6MS4y', 
                        content_type = 'application/pdf', 
                        size_bytes = 1024, 
                        inline = False, 
                        filename = 'document.pdf', 
                        content_id = '<attachment@example.com>', )
                    ],
        )
        """

    def testV1FolderMessagesMessage(self):
        """Test V1FolderMessagesMessage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
