# coding: utf-8

"""
    Hostinger Email API Python SDK

    API Version: 1.0.0

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_email_api.models.v1_folder_messages_flags_request import V1FolderMessagesFlagsRequest

class TestV1FolderMessagesFlagsRequest(unittest.TestCase):
    """V1FolderMessagesFlagsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1FolderMessagesFlagsRequest:
        """Test V1FolderMessagesFlagsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1FolderMessagesFlagsRequest`
        """
        model = V1FolderMessagesFlagsRequest()
        if include_optional:
            return V1FolderMessagesFlagsRequest(
                add_flags = ["\\Seen","\\Flagged","$forwarded"],
                remove_flags = ["\\Seen"]
            )
        else:
            return V1FolderMessagesFlagsRequest(
        )
        """

    def testV1FolderMessagesFlagsRequest(self):
        """Test V1FolderMessagesFlagsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
