# coding: utf-8

"""
    Hostinger Mail API Python SDK

    API Version: 1.0.2

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_mail_api.models.v1_webhooks_create_request import V1WebhooksCreateRequest

class TestV1WebhooksCreateRequest(unittest.TestCase):
    """V1WebhooksCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1WebhooksCreateRequest:
        """Test V1WebhooksCreateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1WebhooksCreateRequest`
        """
        model = V1WebhooksCreateRequest()
        if include_optional:
            return V1WebhooksCreateRequest(
                name = 'New message notifier',
                description = 'Notifies CRM on new mail',
                events = ["message.received"],
                status = 'active',
                url = 'https://example.com/webhooks/incoming'
            )
        else:
            return V1WebhooksCreateRequest(
                name = 'New message notifier',
                events = ["message.received"],
                url = 'https://example.com/webhooks/incoming',
        )
        """

    def testV1WebhooksCreateRequest(self):
        """Test V1WebhooksCreateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
