# coding: utf-8

"""
    Hostinger Email API Python SDK

    API Version: 1.0.0

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_email_api.models.v1_quota_resource import V1QuotaResource

class TestV1QuotaResource(unittest.TestCase):
    """V1QuotaResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1QuotaResource:
        """Test V1QuotaResource
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1QuotaResource`
        """
        model = V1QuotaResource()
        if include_optional:
            return V1QuotaResource(
                data = hostinger_email_api.models.v1/quota/quota.V1.Quota.Quota(
                    quotas = [
                        hostinger_email_api.models.v1/quota/quota_resource.V1.Quota.QuotaResource(
                            resource_name = 'STORAGE', 
                            usage = 1048576, 
                            limit = 1073741824, 
                            percentage = 0, )
                        ], 
                    total_usage = 1048576, 
                    total_limit = 1073741824, 
                    total_percentage = 0, 
                    supported = True, )
            )
        else:
            return V1QuotaResource(
                data = hostinger_email_api.models.v1/quota/quota.V1.Quota.Quota(
                    quotas = [
                        hostinger_email_api.models.v1/quota/quota_resource.V1.Quota.QuotaResource(
                            resource_name = 'STORAGE', 
                            usage = 1048576, 
                            limit = 1073741824, 
                            percentage = 0, )
                        ], 
                    total_usage = 1048576, 
                    total_limit = 1073741824, 
                    total_percentage = 0, 
                    supported = True, ),
        )
        """

    def testV1QuotaResource(self):
        """Test V1QuotaResource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
