# coding: utf-8

"""
    Hostinger Email API Python SDK

    API Version: 1.0.0

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_mail_api.models.v1_webhooks_update_request import V1WebhooksUpdateRequest

class TestV1WebhooksUpdateRequest(unittest.TestCase):
    """V1WebhooksUpdateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1WebhooksUpdateRequest:
        """Test V1WebhooksUpdateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1WebhooksUpdateRequest`
        """
        model = V1WebhooksUpdateRequest()
        if include_optional:
            return V1WebhooksUpdateRequest(
                name = 'Renamed webhook',
                description = 'Updated description',
                events = ["message.received"],
                status = 'paused',
                url = 'https://example.com/webhooks/new'
            )
        else:
            return V1WebhooksUpdateRequest(
        )
        """

    def testV1WebhooksUpdateRequest(self):
        """Test V1WebhooksUpdateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
