# coding: utf-8

"""
    Hostinger Email API Python SDK

    API Version: 1.0.0

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_mail_api.models.v1_folder_messages_flags_bulk_request import V1FolderMessagesFlagsBulkRequest

class TestV1FolderMessagesFlagsBulkRequest(unittest.TestCase):
    """V1FolderMessagesFlagsBulkRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1FolderMessagesFlagsBulkRequest:
        """Test V1FolderMessagesFlagsBulkRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1FolderMessagesFlagsBulkRequest`
        """
        model = V1FolderMessagesFlagsBulkRequest()
        if include_optional:
            return V1FolderMessagesFlagsBulkRequest(
                uids = [42,43,44],
                add_flags = ["\\Seen","\\Flagged","$forwarded"],
                remove_flags = ["\\Seen"]
            )
        else:
            return V1FolderMessagesFlagsBulkRequest(
                uids = [42,43,44],
        )
        """

    def testV1FolderMessagesFlagsBulkRequest(self):
        """Test V1FolderMessagesFlagsBulkRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
