# coding: utf-8

"""
    Hostinger Mail API Python SDK

    API Version: 1.0.2

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_mail_api.models.v1_folder_messages_message_attachment import V1FolderMessagesMessageAttachment

class TestV1FolderMessagesMessageAttachment(unittest.TestCase):
    """V1FolderMessagesMessageAttachment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1FolderMessagesMessageAttachment:
        """Test V1FolderMessagesMessageAttachment
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1FolderMessagesMessageAttachment`
        """
        model = V1FolderMessagesMessageAttachment()
        if include_optional:
            return V1FolderMessagesMessageAttachment(
                id = 'YXR0YWNobWVudDpJTkJPWDoxMjM6MS4y',
                content_type = 'application/pdf',
                size_bytes = 1024,
                inline = False,
                filename = 'document.pdf',
                content_id = '<attachment@example.com>'
            )
        else:
            return V1FolderMessagesMessageAttachment(
                id = 'YXR0YWNobWVudDpJTkJPWDoxMjM6MS4y',
                content_type = 'application/pdf',
                size_bytes = 1024,
                inline = False,
                filename = 'document.pdf',
                content_id = '<attachment@example.com>',
        )
        """

    def testV1FolderMessagesMessageAttachment(self):
        """Test V1FolderMessagesMessageAttachment"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
