# coding: utf-8

"""
    Hostinger Email API Python SDK

    API Version: 1.0.0

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


import unittest

from hostinger_email_api.models.v1_folder_messages_message_address import V1FolderMessagesMessageAddress

class TestV1FolderMessagesMessageAddress(unittest.TestCase):
    """V1FolderMessagesMessageAddress unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1FolderMessagesMessageAddress:
        """Test V1FolderMessagesMessageAddress
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1FolderMessagesMessageAddress`
        """
        model = V1FolderMessagesMessageAddress()
        if include_optional:
            return V1FolderMessagesMessageAddress(
                name = 'John Doe',
                address = 'john@example.com'
            )
        else:
            return V1FolderMessagesMessageAddress(
                name = 'John Doe',
                address = 'john@example.com',
        )
        """

    def testV1FolderMessagesMessageAddress(self):
        """Test V1FolderMessagesMessageAddress"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
