# coding: utf-8

"""
    Hostinger Mail API Python SDK

    API Version: 1.0.2

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class V1FoldersFolder(BaseModel):
    """
    A folder (IMAP mailbox) in the managed mailbox.
    """ # noqa: E501
    path: StrictStr = Field(description="Full hierarchical folder path including the delimiter.")
    name: StrictStr = Field(description="Leaf name of the folder.")
    delimiter: StrictStr = Field(description="Hierarchy delimiter used by the IMAP server.")
    special_use: Optional[StrictStr] = Field(description="IMAP SPECIAL-USE attribute (RFC 6154). `null` for regular folders.", alias="specialUse")
    message_count: StrictInt = Field(description="Total number of messages in the folder.", alias="messageCount")
    unread_count: StrictInt = Field(description="Number of unread messages in the folder.", alias="unreadCount")
    __properties: ClassVar[List[str]] = ["path", "name", "delimiter", "specialUse", "messageCount", "unreadCount"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of V1FoldersFolder from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if special_use (nullable) is None
        # and model_fields_set contains the field
        if self.special_use is None and "special_use" in self.model_fields_set:
            _dict['specialUse'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of V1FoldersFolder from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "path": obj.get("path"),
            "name": obj.get("name"),
            "delimiter": obj.get("delimiter"),
            "specialUse": obj.get("specialUse"),
            "messageCount": obj.get("messageCount"),
            "unreadCount": obj.get("unreadCount")
        })
        return _obj


