# coding: utf-8

"""
    Hostinger Mail API Python SDK

    API Version: 1.1.0

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from hostinger_mail_api.models.v1_folder_messages_message_address import V1FolderMessagesMessageAddress
from hostinger_mail_api.models.v1_folder_messages_message_attachment import V1FolderMessagesMessageAttachment
from typing import Optional, Set
from typing_extensions import Self

class V1FolderMessagesMessage(BaseModel):
    """
    A message in a folder of the managed mailbox.
    """ # noqa: E501
    uid: StrictInt
    path: StrictStr
    var_date: datetime = Field(alias="date")
    flags: List[StrictStr]
    unseen: StrictBool
    size: StrictInt
    subject: Optional[StrictStr]
    var_from: Optional[V1FolderMessagesMessageAddress] = Field(alias="from")
    to: List[V1FolderMessagesMessageAddress]
    cc: List[V1FolderMessagesMessageAddress]
    bcc: List[V1FolderMessagesMessageAddress]
    message_id: Optional[StrictStr] = Field(alias="messageId")
    in_reply_to: Optional[StrictStr] = Field(alias="inReplyTo")
    attachments: List[V1FolderMessagesMessageAttachment]
    __properties: ClassVar[List[str]] = ["uid", "path", "date", "flags", "unseen", "size", "subject", "from", "to", "cc", "bcc", "messageId", "inReplyTo", "attachments"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of V1FolderMessagesMessage from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of var_from
        if self.var_from:
            _dict['from'] = self.var_from.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in to (list)
        _items = []
        if self.to:
            for _item_to in self.to:
                if _item_to:
                    _items.append(_item_to.to_dict())
            _dict['to'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in cc (list)
        _items = []
        if self.cc:
            for _item_cc in self.cc:
                if _item_cc:
                    _items.append(_item_cc.to_dict())
            _dict['cc'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in bcc (list)
        _items = []
        if self.bcc:
            for _item_bcc in self.bcc:
                if _item_bcc:
                    _items.append(_item_bcc.to_dict())
            _dict['bcc'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in attachments (list)
        _items = []
        if self.attachments:
            for _item_attachments in self.attachments:
                if _item_attachments:
                    _items.append(_item_attachments.to_dict())
            _dict['attachments'] = _items
        # set to None if subject (nullable) is None
        # and model_fields_set contains the field
        if self.subject is None and "subject" in self.model_fields_set:
            _dict['subject'] = None

        # set to None if var_from (nullable) is None
        # and model_fields_set contains the field
        if self.var_from is None and "var_from" in self.model_fields_set:
            _dict['from'] = None

        # set to None if message_id (nullable) is None
        # and model_fields_set contains the field
        if self.message_id is None and "message_id" in self.model_fields_set:
            _dict['messageId'] = None

        # set to None if in_reply_to (nullable) is None
        # and model_fields_set contains the field
        if self.in_reply_to is None and "in_reply_to" in self.model_fields_set:
            _dict['inReplyTo'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of V1FolderMessagesMessage from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "uid": obj.get("uid"),
            "path": obj.get("path"),
            "date": obj.get("date"),
            "flags": obj.get("flags"),
            "unseen": obj.get("unseen"),
            "size": obj.get("size"),
            "subject": obj.get("subject"),
            "from": V1FolderMessagesMessageAddress.from_dict(obj["from"]) if obj.get("from") is not None else None,
            "to": [V1FolderMessagesMessageAddress.from_dict(_item) for _item in obj["to"]] if obj.get("to") is not None else None,
            "cc": [V1FolderMessagesMessageAddress.from_dict(_item) for _item in obj["cc"]] if obj.get("cc") is not None else None,
            "bcc": [V1FolderMessagesMessageAddress.from_dict(_item) for _item in obj["bcc"]] if obj.get("bcc") is not None else None,
            "messageId": obj.get("messageId"),
            "inReplyTo": obj.get("inReplyTo"),
            "attachments": [V1FolderMessagesMessageAttachment.from_dict(_item) for _item in obj["attachments"]] if obj.get("attachments") is not None else None
        })
        return _obj


