# coding: utf-8

"""
    Hostinger Mail API Python SDK

    API Version: 1.0.2

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class V1FolderMessagesSearchRequest(BaseModel):
    """
    Search criteria. All fields optional; combine to narrow results.
    """ # noqa: E501
    since: Optional[date] = None
    before: Optional[date] = None
    flags: Optional[List[Annotated[str, Field(min_length=1, strict=True, max_length=255)]]] = None
    uid: Optional[StrictStr] = None
    subject: Optional[Annotated[str, Field(strict=True, max_length=1024)]] = None
    var_from: Optional[Annotated[str, Field(strict=True, max_length=320)]] = Field(default=None, alias="from")
    to: Optional[Annotated[str, Field(strict=True, max_length=320)]] = None
    cc: Optional[Annotated[str, Field(strict=True, max_length=320)]] = None
    body: Optional[Annotated[str, Field(strict=True, max_length=1024)]] = None
    header: Optional[Annotated[str, Field(strict=True, max_length=1024)]] = None
    larger: Optional[Annotated[int, Field(strict=True, ge=0)]] = None
    smaller: Optional[Annotated[int, Field(strict=True, ge=0)]] = None
    text: Optional[Annotated[str, Field(strict=True, max_length=1024)]] = None
    __properties: ClassVar[List[str]] = ["since", "before", "flags", "uid", "subject", "from", "to", "cc", "body", "header", "larger", "smaller", "text"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of V1FolderMessagesSearchRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of V1FolderMessagesSearchRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "since": obj.get("since"),
            "before": obj.get("before"),
            "flags": obj.get("flags"),
            "uid": obj.get("uid"),
            "subject": obj.get("subject"),
            "from": obj.get("from"),
            "to": obj.get("to"),
            "cc": obj.get("cc"),
            "body": obj.get("body"),
            "header": obj.get("header"),
            "larger": obj.get("larger"),
            "smaller": obj.get("smaller"),
            "text": obj.get("text")
        })
        return _obj


