# coding: utf-8

"""
    Hostinger Email API Python SDK

    API Version: 1.0.0

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt
from typing import Any, ClassVar, Dict, List
from hostinger_mail_api.models.v1_quota_quota_resource import V1QuotaQuotaResource
from typing import Optional, Set
from typing_extensions import Self

class V1QuotaQuota(BaseModel):
    """
    Storage and message quota usage for the managed mailbox.
    """ # noqa: E501
    quotas: List[V1QuotaQuotaResource] = Field(description="Per-resource quota breakdown reported by the IMAP server.")
    total_usage: StrictInt = Field(description="Aggregate storage usage across all resources, in bytes.", alias="totalUsage")
    total_limit: StrictInt = Field(description="Aggregate storage limit across all resources, in bytes.", alias="totalLimit")
    total_percentage: StrictInt = Field(description="Aggregate storage usage as a percentage of the total limit.", alias="totalPercentage")
    supported: StrictBool = Field(description="Whether the IMAP server reports quota information for this mailbox.")
    __properties: ClassVar[List[str]] = ["quotas", "totalUsage", "totalLimit", "totalPercentage", "supported"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of V1QuotaQuota from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in quotas (list)
        _items = []
        if self.quotas:
            for _item_quotas in self.quotas:
                if _item_quotas:
                    _items.append(_item_quotas.to_dict())
            _dict['quotas'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of V1QuotaQuota from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "quotas": [V1QuotaQuotaResource.from_dict(_item) for _item in obj["quotas"]] if obj.get("quotas") is not None else None,
            "totalUsage": obj.get("totalUsage"),
            "totalLimit": obj.get("totalLimit"),
            "totalPercentage": obj.get("totalPercentage"),
            "supported": obj.get("supported")
        })
        return _obj


