# coding: utf-8

"""
    Hostinger Mail API Python SDK

    API Version: 1.1.0

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class V1SendAttachment(BaseModel):
    """
    Attachment payload for outgoing mail. Supports regular attachments and inline images linked via Content-ID.
    """ # noqa: E501
    filename: StrictStr
    content: StrictStr = Field(description="Attachment body. Base64-encoded by default; set encoding to switch.")
    content_type: Optional[StrictStr] = Field(default=None, alias="contentType")
    cid: Optional[StrictStr] = Field(default=None, description="Content-ID for inline images. Reference from HTML as <img src=\"cid:logo\">.")
    encoding: Optional[StrictStr] = Field(default=None, description="Encoding of content. Defaults to base64.")
    __properties: ClassVar[List[str]] = ["filename", "content", "contentType", "cid", "encoding"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of V1SendAttachment from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of V1SendAttachment from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "filename": obj.get("filename"),
            "content": obj.get("content"),
            "contentType": obj.get("contentType"),
            "cid": obj.get("cid"),
            "encoding": obj.get("encoding")
        })
        return _obj


