# coding: utf-8

"""
    Hostinger Email API Python SDK

    API Version: 1.0.0

    NOTE: This file is auto-generated, DO NOT EDIT THIS FILE MANUALLY!
    If you want to contribute or request a new feature, please create an issue or pull request on https://github.com/hostinger/api
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class V1WebhooksWebhook(BaseModel):
    """
    Webhook configured for a managed mailbox.
    """ # noqa: E501
    id: StrictStr = Field(description="Unique webhook identifier (UUID v7).")
    account_resource_id: Annotated[str, Field(strict=True)] = Field(description="Resource ID of the mailbox this webhook is attached to.", alias="accountResourceId")
    mailbox: StrictStr = Field(description="Email address of the mailbox.")
    name: Annotated[str, Field(strict=True, max_length=255)]
    description: Optional[StrictStr]
    events: List[StrictStr]
    status: StrictStr
    url: Annotated[str, Field(strict=True, max_length=2048)]
    created_at: datetime = Field(alias="createdAt")
    updated_at: datetime = Field(alias="updatedAt")
    __properties: ClassVar[List[str]] = ["id", "accountResourceId", "mailbox", "name", "description", "events", "status", "url", "createdAt", "updatedAt"]

    @field_validator('account_resource_id')
    def account_resource_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^AC[A-Za-z0-9]+$", value):
            raise ValueError(r"must validate the regular expression /^AC[A-Za-z0-9]+$/")
        return value

    @field_validator('events')
    def events_validate_enum(cls, value):
        """Validates the enum"""
        for i in value:
            if i not in set(['message.received']):
                raise ValueError("each list item must be one of ('message.received')")
        return value

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['active', 'paused', 'disabled']):
            raise ValueError("must be one of enum values ('active', 'paused', 'disabled')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of V1WebhooksWebhook from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of V1WebhooksWebhook from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "accountResourceId": obj.get("accountResourceId"),
            "mailbox": obj.get("mailbox"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "events": obj.get("events"),
            "status": obj.get("status"),
            "url": obj.get("url"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt")
        })
        return _obj


